""" Open5GS Actuator Manager

	This module implements a simple Actuator Manager for Open5GS network core.
	It discovers networking relationships between network functions in the core and
	the connected data network.

	UE ---- gNodeB ----- UPF ------- data network

	The actuator-specific configuration includes:
		
		- ``auth``:

			- ``api_key``: A token generated by the Kubernetes cluster for the service account used for context discovery.
			- ``host``: DNS name or IP address of the Kubernetes endpoint (including port number)

		- ``config``:
		
			- ``cacert``: Location of the CA certificate used to sign the endpoint HTTPS certificate (if not installed in the local host).
 			- ``namespaces``: list of namespace names to query (all namespace if not given).

"""

from dotenv import dotenv_values

import logging
import yaml
import ipaddress
from glob import glob

from otupy.profiles import slpf
from otupy.profiles.ctxd.data.application import Application
from otupy.types.data.ipv4_addr import IPv4Addr


from otupy.actuators.xbom.xbom_actuator import XBOMActuator
from otupy.profiles.xbom.data.consumer import Consumer
from otupy.profiles.xbom.data.network import Network
from otupy.profiles.xbom.data.name import Name
from otupy.profiles.xbom.data.service import Service
from otupy.profiles.xbom.data.service_type import ServiceType
from otupy.profiles.xbom.data.peer import Peer
from otupy.profiles.xbom.data.peer_role import PeerRole
from otupy.profiles.xbom.data.link import Link
from otupy.profiles.xbom.data.link_type import LinkType
from otupy.profiles.ctxd.data.mobile_network import MobileNetwork
from otupy.profiles.ctxd.data.ethernet_network import EthernetNetwork
from otupy.profiles.xbom.data.iot import IOT
from otupy.profiles.xbom.data.network_type import NetworkType

from otupy import ArrayOf, IPv4Net, IPv6Net, actuator_implementation
import otupy.profiles.xbom as xbom

logger = logging.getLogger(__name__)


@actuator_implementation("xbom-open5gs")
class XBOMActuator_open5gs(XBOMActuator):
	""" Open5GS Actuator Manager

		Extend the base `XBOMActuator` to retrieve services and links for a Open5GS core. 
		
		A bit of understanding about this actuator. A network operator deploys its network
		and provides the xbom service. There are alternative deployment ways: in servers, 
		in virtual machines, as cloud native application. We currently assume the cloud
		native deployment in Kubernetes, and this means we have the manifest files available
		to create the links to K8S resources. Support for additional deployment options
		should be added in the future, if necessary.

	"""

	config_file : any = None #configuration file path

	def __init__(self, **kwargs):
		""" Initialization

			The necessary parameters are:
			- auth: Authentication information to connect to a Kubernetes cluster
			Optional parameters:
			- namespaces: List of namespaces which resources are to be discovered. If not provided, resources from all namespaces will be discovered.
			- dns: DNS name for the kubernets cloud
		"""
		super().__init__(**kwargs)

		try:
			self._load_open5gs_config(**kwargs)
			self.configured = True
		except:
			self.configured = False


		try:
			self.service_name=kwargs['config']['name']
		except:
			self.service_name="open5gs"


	def discover_services(self):
		""" Mobile network + data network 

			This function creates two services for the mobile network and its backing data network
			Additionally, it creates the users of the network.
		"""
		if not self.configured:
			return

		mobile = MobileNetwork({'name': self.net_name, 'mcc': self.mcc, 'mnc': self.mnc,
				'netv4nets': [IPv4Net(self.mobilenetv4)], 'netv6nets': [IPv6Net(self.mobilenetv6)]})
		mobilenet = Network(name="Open5Gs", description="Open5Gs core and UERASIM RAN",
				type=NetworkType(mobile))

		self.services.append(Service(name=Name(self.service_name), type=ServiceType(mobilenet),
				subservices=ArrayOf(Name)(self.mobile_services), owner=self.owner, release=None))

		data = EthernetNetwork({'netv4nets': [IPv4Net(self.datanetv4)]})
		datanet = Network(name="DataNetwork", description="Open5Gs data network",
				type=NetworkType(data))

		self.services.append(Service(name=Name('datanetwork'), type=ServiceType(datanet),
					subservices=ArrayOf(Name)(), owner=self.owner, release=None))

		for u in self.users:
			iot = IOT(name=u['name'], description="Mobile phone", type="phone")
			self.services.append(Service(name=Name(u['name']), type=ServiceType(iot),
					subservices=ArrayOf(Name)(), owner=self.owner, release=None))


	def discover_links(self):
		if not self.configured:
			return

		peer = Peer(service_name=Name(self.service_name), 
					role=PeerRole.forwarding, # Network transport packets
					consumer=None)
		for u in self.users:
			description="User "+str(u['name'])+" connected to network "+str(peer.service_name)
			self.links.append(Link(name=u['name'], description=description,
						link_type=LinkType.packet_flow, peers=ArrayOf(Peer)([peer])))

	def _load_open5gs_config(self, **kwargs):
		if kwargs['config']['deployment'] == 'kubernetes' and \
				kwargs['config']['manager'] == 'cn5t':
			self._load_open5gs_cn5t(**kwargs)
		else:
			raise NotImplementedError("Unsupported deployment/manager option")


	def _load_open5gs_cn5t(self, **kwargs):

		# Load configuration parameters
		try:
			config=dotenv_values(kwargs['config']['config_dir']+'/config/cn5t.env')
		except:
			logger.error("Unable to load cn5t configuration file")
			self.configured=False
		self.datanetv4=config['DATANETWORK1']
		self.k8s_domain=config['K8S_DOMAIN']
		self.k8s_namespace=config['K8S_NAMESPACE']
		malicious_users=config['DDOS_REPLICAS']
		licit_users=config['CURL_REPLICAS']
		self.users = []
		for u in range(0, int(licit_users)):
			self.users.append({'name': 'curl'+str(u)})
		for u in range(0, int(malicious_users)):
			self.users.append({'name': 'curl'+str(u)})

		with open(kwargs['config']['config_dir']+"/templates/config/30_open5gs/amf-configmap.yaml") as file:
			c=yaml.safe_load(file)
		for k,v in c['data'].items():
			amf_conf=yaml.safe_load(c['data'][k])

		self.net_name=amf_conf['amf']['network_name']['full']
		for i in amf_conf['amf']['plmn_support']:
			self.mcc=str(i['plmn_id']['mcc'])
			self.mnc=i['plmn_id']['mnc']

		with open(kwargs['config']['config_dir']+"/templates/config/30_open5gs/upf-configmap.yaml") as file:
			c=yaml.safe_load(file)
		for k,v in c['data'].items():
			upf_conf=yaml.safe_load(c['data'][k])

		for i in upf_conf['upf']['subnet']:
			ip = ipaddress.ip_network(i['addr'],strict=False)
			print("ip: ", ip)
			if type(ip) == ipaddress.IPv4Network:
				self.mobilenetv4=ip
			else:
				self.mobilenetv6=ip

		self.mobile_services = []
		print("parsing: ", glob(kwargs['config']['config_dir']+"/templates/network/30_open5gs/*.yaml"))
		for file in glob(kwargs['config']['config_dir']+"/templates/network/30_open5gs/*.yaml"):
			try:
				with open(file) as f:
					configs = yaml.load_all(f, Loader=yaml.FullLoader)
					for c in configs:
						try:
							if c['kind'] == "Service":
								name=c['metadata']['name']+".svc."+self.k8s_namespace+"."+self.k8s_domain
								self.mobile_services.append(name)
						except Exception as e:
							pass
			except Exception as e: 
				logger.error("Unable to parse %s: %s", file, e)
	



