""" Kubernetes Actuator Manager

	This module implements a simple Actuator Manager for Kubernetes.
	It discovers Kubernetes resources by invoking its APIs. 

	The documentation of the Kubernetes API is here: https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/CoreV1Api.md.


	The actuator-specific configuration includes:
		
		- ``auth``:

			- ``api_key``: A token generated by the Kubernetes cluster for the service account used for context discovery.
			- ``host``: DNS name or IP address of the Kubernetes endpoint (including port number)

		- ``config``:
		
			- ``dns``: DNS suffix for this cluster (needed to create unique names for resources)
			- ``cacert``: Location of the CA certificate used to sign the endpoint HTTPS certificate (if not installed in the local host).
			- ``cni``: CNI configuration. It must include specific address ranges if the original manifest file is not available. The ``file`` stanza is alternative to the address ranges (if supplied, it takes precedence).
			
				- ``cluster-cidr``: the network address used for cluster communication (inter-pod).
				- ``service-cluster-ip-range``: the network address used for services.
				- ``file``: Location of the Kube controller manager manifest file that can be parsed.

 			- ``namespaces``: list of namespace names to query (all namespace if not given).

"""

import socket
import subprocess
import json
import yaml
import os
import logging
import sys
import ipaddress

from otupy.profiles import slpf
from otupy.profiles.ctxd.data.application import Application
from otupy.types.data.ipv4_addr import IPv4Addr
from otupy.types.data.uri  import URI

from kubernetes import config, client
from kubernetes.client.rest import ApiException

from urllib.parse import urlparse

from otupy.actuators.ctxd.ctxd_actuator import CTXDActuator

from otupy.profiles.ctxd import *

from otupy.types.data.hostname import Hostname
from otupy.types.data.l4_protocol import L4Protocol



from otupy import ArrayOf, Nsid, Version,Actions, Response, StatusCode, StatusCodeDescription, Features, ResponseType, Feature, actuator_implementation
import otupy.profiles.ctxd as ctxd

from otupy.profiles.ctxd.data.name import Name
from otupy.profiles.ctxd.data.service import Service
from otupy.profiles.ctxd.data.link import Link

logger = logging.getLogger(__name__)


@actuator_implementation("ctxd-kubernetes")
class CTXDActuator_kubernetes(CTXDActuator):
	""" Kubernetes Actuator Manager

		Extend the base `CTDXActuator` to retrieve services and links for a Kubernetes cluster. Currently discovery is mostly limited to pods,
		nodes, and containers. It should be extended in future releases with additional resources (e.g., services and file systems).

	"""

	namespace = [] #it contains only the name of the namespaces
	""" Namespaces list"""
	api_client : any = None #api client for kubernetes
	config_file : any = None #configuration file path
	kube_context : any = None #kubernetes context

	def __init__(self, auth, **kwargs):
		""" Initialization

			The necessary parameters are:
			- auth: Authentication information to connect to a Kubernetes cluster
			Optional parameters:
			- namespaces: List of namespaces which resources are to be discovered. If not provided, resources from all namespaces will be discovered.
			- dns: DNS name for the kubernets cloud
		"""
		kwargs['auth']=auth
		super().__init__(**kwargs)

		self.namespaces = kwargs['config']['namespaces'] if 'config' in kwargs and 'namespaces' in kwargs['config'] else None
		self.dns = kwargs['config']['dns'] if 'config' in kwargs and 'dns' in kwargs['config'] else None
		self.cniconfig = kwargs['config']['cni'] if 'config' in kwargs and 'cni' in kwargs['config'] else None

		self.nats = {} # Keep a map of NAT associated to each pod
		self.nodes = {} # Keep a map of nodes hosting each pod
		self.routers = {} # Keep a map of routers for each pod
		self.networks = {} # Keep a map of networks for each pod

		self._setup_cni()
		self._connect_to_kubernetes()

	def discover_context(self):
		""" Discover services and links

			Implements the base class interface to update services and links
		"""
		self.discover_services()
		self.discover_links()


	def discover_services(self):
		""" Discovers K8S services

			Implements the required method to discover services. Currently it discover:
			- K8S base services (e.g., dns)
			- Pods in selected namespaces
			- Nodes
			- Namespaces available
		"""
		self._discover_k8s_services()
		self._discover_k8s_pods()
		self._discover_k8s_namespaces()		
		self._discover_k8s_networks()
		self._discover_pod_networks()
		self._discover_k8s_routers()
#self._discover_k8s_nodes() We don't create services for nodes, since these should be created by another Actuator
		# TODO: Discover:
		# - images

	def discover_links(self):
		""" Automatically discover links between Kubernetes components

			The current implementation discovers links between:
			- Kubernetes and nodes
			- Kubernetes  and pods 
			- Pods and containers
			- Network Policy firewall and pods
		"""
		self._discover_k8s_links_nodes()
		self._discover_k8s_links_pods()
		self._discover_networkfunctions_links_nodes()
		self._discover_pod_links_nodes()
		self._discover_pod_links_containers()
		self._discover_pod_links_networks()
		self._discover_k8s_links_np()
		self._discover_np_links_pods()


	def _discover_k8s_namespaces(self):
		namespaces = self._k8s_namespaces_list()

		# There might be a null configuration
		if namespaces is []:
			return

		# WARNING: Namespaces are not converted to services so far!!!


	def _k8s_namespaces_list(self):
		namespace_list = []
		try:
			namespace_list = self.api_client.list_namespace(field_selector="status.phase=Active").items
		except ApiException as e: # Fails without cluster-wide scope
			logger.warn("Unable to retrieve namespace list (do you have cluster-wide access?)")
			logger.debug("Reason: %s", e)
			return []

		if self.namespaces is None: # Retrieve all namespaces
			return namespace_list
		else:
			return [ ns for ns in namespace_list if ns.metadata.name in self.namespaces ]

		

	def _discover_k8s_services(self):
		""" Discover Kubernetes services 

			Loops through provided namespaces and returns the services found.
			Services are NATs in front of Pods.

			Rules are currently saved as strings. TODO: create data structures for NAT rules.
		"""

		# Kubernetes services
		# ---------------------------------
		cloud_services = self._k8s_service_list(namespaces=self.namespaces)
		kube_api_found = False
		self.nats = {}

		def _update_endpoints(endpoints, ip, port):
			if len(endpoints) > 0:
				endpoints = endpoints + ", "
			return endpoints + ip + "/" + str(port)

		k8s_services = ArrayOf(Name)()
		for service in cloud_services:
			rules = ArrayOf(str)()
			if service.spec.selector is not None:
				for k,v in service.spec.selector.items():
					# Assume only 1 field selector is present
					label_selector= k + "=" + v
				pods = self._k8s_pod_list(label_selector=label_selector)
			else:
				pods = None
			match service.spec.type:
				case "ClusterIP":
					for ip in ( [] if service.spec.cluster_i_ps is None else service.spec.cluster_i_ps ) +  ( [] if service.spec.external_i_ps is None else service.spec.external_i_ps):
						for port in service.spec.ports:
							endpoints=""
							if pods is not None:
								for p in pods:
									if p.metadata.namespace == service.metadata.namespace: 
										endpoints = _update_endpoints(endpoints, p.status.pod_ip,  str(port.target_port))
							else:
								try:
									eps = self._k8s_endpoint_list(namespace=service.metadata.namespace, service=service.metadata.name)
									for e in eps.items:
										for s in e.subsets:
											for a in s.addresses:
												for p in s.ports:
													endpoints = _update_endpoints(endpoints, a.ip, str(p.port))
								except:
									logger.warn("Unable to retrieve endpoint for %s", service.metadata.name)
							rules.append( "DNAT: " + ip + ":" + str(port.port) + " (" + port.name + ") -> " + endpoints )
				case "NodePort":
				  	# Retrieve node address
					for port in service.spec.ports:
						endpoints=""
						for p in pods:
							endpoints = _update_endpoints(endpoints, p.status.host_ip ,str(port.target_port))
						rules.append( "DNAT: " + ip + ":" + str(port.node_port) + " (" + port.name + ") -> " + endpoints )
				case _:
					# TODO: Retrieve the IP address of the nodes hosting the pod implementing the service
					logger.warn("Unmanaged service type %s for for %s",service.spec.type, service.metadata.name)

			try:
				# Try to detect the kubeapi service (if cluster-wide visibility is available)
				if ( service.metadata.labels['component'] == "apiserver" and
						service.metadata.labels['provider'] == "kubernetes" ):
					# This is the apiserver for Kubernetes; subservices are kubelets
					description="Kubernetes API Service"
					kube_api_found=True
			except:
					description="Kubernetes service " + service.spec.type
			
#			# Retrieve the list of pods served by this namespace
#			ep = self._k8s_endpoint_list(namespace=service.metadata.namespace, service=service.metadata.name)
#			subservices = ArrayOf(Name)()
#			for e in ep.items:
#				for s in e.subsets:
#					try:
#						for a in s.addresses:
#							subservices.append(self._k8s_dns_name(name=a.target_ref.name, 
#									namespace=service.metadata.namespace,
#									resource_type="pod"))
#					except:
#						pass

			nat = NetworkFunction(name=service.metadata.name,
					description=description,
					id=service.metadata.uid,
					type=NetworkFunctionType(NAT(rules=rules)))
			name=Name(Hostname(self._k8s_dns_name(nat.name, service.metadata.namespace, "svc")))
			nat_service = (Service(name=name, type=ServiceType(nat), 
						namespace=service.metadata.namespace,
						subservices=None, owner=self.owner, release=None))
			self.services.append(nat_service)
			for p in pods:
				pod_ref=str(Name(Hostname(self._k8s_dns_name(p.metadata.name, p.metadata.namespace, "pod"))))
				self.nats[pod_ref]=nat_service


# Not sure this is a good idea, once I understood K8S svc are NATs
#		# Kube API service
#		# -----------------
#		# Add the API service if not found automatically
#		u = urlparse(self.auth['host'])
#		app = (API(description="Kubernetes API Service",
#					name=self._k8s_dns_name(name="kubernetes",namespace="default",resource_type="svc"),
#					endpoints=ArrayOf(Endpoint)([Endpoint(description=u.scheme, endpoint_type="kubeapi", 
#						  									transport="TCP", transfer=u.scheme, encoding=None,
#															uri=self.auth['host'])]),
#					id=None, provider=self.owner ))
#		logger.debug("Found k8s service: %s", str(app.name))
#		# TODO: Add software release (maybe with its SBOM)
#		# TODO: What are subservices of a Service? Pods? 
#		name=Name(Hostname(self._k8s_dns_name(app.name, service.metadata.namespace, "svc")))
#		self.services.append(Service(name=name, type=ServiceType(app), #links=ArrayOf(Link)(),
#					namespace=service.metadata.namespace,
#					subservices=subservices, owner=self.owner, release=None))
	

	def _discover_k8s_networks(self):
		""" Create cluster networks

			This function artifically creates two cluster networks based on configuration
			information, since there is no API to query the cni.
		"""

		# Cluster network
		ipnets = ArrayOf(IPNetAddress)([IPNetAddress(self.cni_cluster_cidr), IPNetAddress(self.cni_service_cidr)])
		eth = EthernetNetwork({'nets': ipnets})
		net = Network(name='k8s-pod-network', description="Kubernetes cluster network",
				id=None, type=NetworkType(eth))
	
		# The cluster network is implemented by routers hosted at each node
		subservices=ArrayOf(Name)()
		k8s_nodes = self._k8s_node_list()
		for n in k8s_nodes:
			subservices.append(self._k8s_dns_name(name=n.metadata.name, namespace=None, resource_type="router"))

		self.services.append(Service(name=Name(Hostname(self._k8s_dns_name(name=net.name, namespace=None, resource_type="network"))) , 
					type=ServiceType(net),
				subservices=subservices, owner=self.owner, release=None))

	def _discover_pod_networks(self):
		# Look for additional multus networks.
		# I could not understand whether there is function in the kubernetes library
		# to use the k8s.cni.cncf.io/v1 for retrieving network-attachment-definition 
		# In any case, since in such configuration there is no network address, I parse
		# pod annotations
		self.networks = {}
		for pod in self._k8s_pod_list():
			podname=str(Name(Hostname(self._k8s_dns_name(name=pod.metadata.name, namespace=pod.metadata.namespace,
								resource_type="pod"))))
			self.networks[podname] = []
			if 'k8s.v1.cni.cncf.io/networks' in pod.metadata.annotations:
				for net in json.loads(pod.metadata.annotations['k8s.v1.cni.cncf.io/networks']):
					if 'name' in net and net['name'] != "k8s-pod-network":
						netname=Name(Hostname(self._k8s_dns_name(name=net['name'], 
																			namespace=pod.metadata.namespace, 
																			resource_type="network")))
						net_services = self.get_services(name=netname, namespace=pod.metadata.namespace, filter=Network)
						if len(net_services) == 0: # Not registered yet
							ipnets = ArrayOf(IPNetAddress)()
							if 'ips' in net:
								for ip in net['ips']:
									ipnets.append(ipaddress.ip_network(ip, strict=False))	
							# TODO: This is an over-simplifcation, since multiple types of network can be present
							eth = EthernetNetwork({'nets': ipnets})
							net = Network(name=net['name'], description="Kubernetes network " + str(netname),
								id=None, type=NetworkType(eth))
	
							self.services.append(Service(
										name=netname,
										namespace=pod.metadata.namespace,
										type=ServiceType(net),
										subservices=ArrayOf(Name)(), owner=self.owner, release=None))
						else:
							print("checking")
							for mynet in net_services:
								# Check if ips are already registered
								# TODO: Manage additional network types
								for ip1 in mynet.type.getObj().type.getObj()['nets']:
									if 'ips' in net:
										for ip2 in net['ips']:
											found = False
											if str(ip1) == str(ipaddress.ip_network(ip2,strict=False)):
												found=True
											print('found: ', found)
											if not found:
												 mynet.type.getObj().type.getObj()['nets'].append(ip2)
						self.networks[podname].append(netname)
									


	def _k8s_service_list(self, namespaces=None):
		""" Discover k8s services in the given namespace

			:param namespace: the namespace name
		"""
		try:
			if namespaces is None:
				return self.api_client.list_service_for_all_namespaces().items 
		except ApiException as e:
			logger.warn("Unable to retrieve service list for all namespaces")
			logger.debug("Reason: %s",e)
			return []

		try:
			service_list=[]
			for n in namespaces:
				# This works even without cluster scope
				service_list+=self.api_client.list_namespaced_service(namespace=n).items
		except ApiException as e:
			logger.warn("Unable to retrieve service list for namespace %s: %s",n, e)
		
		return service_list	

	def _k8s_endpoint_list(self, namespace, service=None):
		if service is not None:
			fs = "metadata.name=="+service
		else:
			fs = None

		try:
			return self.api_client.list_namespaced_endpoints(namespace=namespace, field_selector=fs)
		except:
			logger.warn("Unable to retrieve endpoints for namespace: %s", namespace)
			return []

	
	def _k8s_pod_node(self, pod):
		pods = self.api_client.list_namespaced_pod(namespace=pod.namespace, field_selector="metadata.name="+str(pod.name))
		for p in pods.items:
			# Just one item will be present because the pod name is unique in the same namespace
			return p.spec.node_name
			

	def _discover_pod_links_nodes(self):
		""" Add links between pods and nodes where they are hosted 
		"""
		k8s_pods = self.get_services(filter=Pod)

		# If nodes were discovered, I can safely assume to have cluster-wide visibility
		for p in k8s_pods:
			node = self._k8s_pod_node(p.type.getObj())
			consumer=self.get_consumer(Name(node))
			# We assume the node name is the same as the service created by its actuator
			peer = Peer(service_name=Name(Hostname(node)),
						role=PeerRole.host, # Node hosts pods
						consumer=consumer)
			description="Pod "+str(p.name)+" hosted on "+str(peer.service_name)
			self.links.append(Link(name=p.name, description=description, role=PeerRole.guest,
						link_type=LinkType.hosting, peers=ArrayOf(Peer)([peer])))

	def _discover_pod_links_containers(self):
		""" Add links between pods and containers they contain
		"""
		k8s_pods = self.get_services(filter=Pod)

		for p in k8s_pods:
			for c in p.subservices:
				peer = Peer(service_name=c, role=PeerRole.contained, consumer=None)
				description="Container "+str(c)+" in pod "+str(p.name)
				self.links.append(Link(name=p.name, description=description, role=PeerRole.guest,
							link_type=LinkType.containing, peers=ArrayOf(Peer)([peer])))
				
	def _discover_pod_links_networks(self):
		""" Add links between pods and the cluster network

			If a service for the pod is present, we also add a NAT function in between.
			TODO: may we also add a Firewall function in between?

			(Pod) --- (NAT) --- (k8s-pod-network )
								 -------- (Router)
		"""
		k8s_pods = self.get_services(filter=Pod)
		nets = self.get_services(name=Name(Hostname(self._k8s_dns_name("k8s-pod-network", resource_type="network"))), filter=Network)

		for p in k8s_pods:
			for net in nets:
				if str(p.name) in self.nats:
					nat = self.nats[str(p.name)]
					# Add NAT between pod and cluster network
					peer = Peer(service_name=nat, role=PeerRole.forwarding, consumer=None)
					description="Pod "+str(p.name)+" attached to NAT " + str(nat)
					self.links.append(Link(name=p.name, description=description, role=PeerRole.endpoint,
								link_type=LinkType.packet_flow, peers=ArrayOf(Peer)([peer])))
					peer = Peer(service_name=net.name, role=PeerRole.forwarding, consumer=None)
					description="NAT "+str(nat)+" attached to cluster network"
					self.links.append(Link(name=nat, description=description, role=PeerRole.forwarding,
								link_type=LinkType.packet_flow, peers=ArrayOf(Peer)([peer])))
					if str(p.name) in self.routers:
						router=self.routers[str(p.name)]
						peer = Peer(service_name=router, role=PeerRole.forwarding, consumer=None)
						description="NAT "+str(nat)+" attached to router " + str(router)
						self.links.append(Link(name=nat, description=description, role=PeerRole.forwarding,
									link_type=LinkType.packet_flow, peers=ArrayOf(Peer)([peer])))
				else: # No NAT: pod attached directly to cluster network
					peer = Peer(service_name=net.name, role=PeerRole.forwarding, consumer=None)
					description="Pod "+str(p.name)+" attached to cluster network"
					self.links.append(Link(name=p.name, description=description, role=PeerRole.endpoint,
								link_type=LinkType.packet_flow, peers=ArrayOf(Peer)([peer])))
					if str(p.name) in self.routers:
						router=self.routers[str(p.name)]
						peer = Peer(service_name=router, role=PeerRole.forwarding, consumer=None)
						description="Pod "+str(p.name)+" attached to router " + str(router)
						self.links.append(Link(name=p.name, description=description, role=PeerRole.endpoint,
									link_type=LinkType.packet_flow, peers=ArrayOf(Peer)([peer])))
			# Other networks:
			for netname in self.networks[str(p.name)]:
				peer = Peer(service_name=netname, role=PeerRole.forwarding, consumer=None)
				description="Pod "+str(p.name)+" attached to network " + str(netname)
				self.links.append(Link(name=p.name, description=description, role=PeerRole.endpoint,
							link_type=LinkType.packet_flow, peers=ArrayOf(Peer)([peer])))





	def _discover_k8s_links_nodes(self):
		""" Discover K8S links to nodes

			Kube-api is hosted on master
			Kubelets are hosted on slaves(/master)
			
			For now, a simplification is used and only Kubernetes hosted on master is reported
		"""

		k8s_service = self.get_services(name=Name(Hostname(self._k8s_dns_name(name='kubernetes',
																								namespace="default",
																								resource_type="svc"))),
													filter=API)

		try:
			# Try to get the master node from kubernets
			master = (self._k8s_node_list(label_selector="node-role.kubernetes.io/control-plane"))[0].metadata.name

			k8s_nodes = self._k8s_node_list()
	
			for k in k8s_service:
				for n in k8s_nodes:
					consumer=self.get_consumer(n.metadata.name)
					peer = Peer(service_name=n.metadata.name,
								role=PeerRole.host, # K8S is hosted on master node
								consumer=consumer)
					description="Kubernetes API Server hosted on "+str(n.metadata.name)
					self.links.append(Link(name=k.name, description=description, role=PeerRole.guest,
								link_type=LinkType.hosting, peers=ArrayOf(Peer)([peer])))

		except Exception as e:
			# Otherwise assign the 
			pass
			
	def _discover_networkfunctions_links_nodes(self):
		""" Assign routers to nodes 
		"""
		nfs = self.get_services(filter=NetworkFunction)
		nodes = self._k8s_node_list()

		for nf in nfs:
			if( type(nf.type.getObj().type.getObj()) == Router):
				for n in nodes:
					if nf.type.getObj().name == n.metadata.name:
						peername=Name(Hostname(n.metadata.name))
						description="Router " + str(nf.name) + " hosted on "+ str(peername)
			elif ( type(nf.type.getObj().type.getObj()) == NAT):
				for pod, nat in self.nats.items():
					if nat.name == nf.name:
						try:
							peername=self.nodes[pod]
							description="NAT " + str(nf.name) + " hosted on "+ str(peername)
						except Exception as e:
							continue
			else:
			 	continue
			consumer = self.get_consumer(peername)
			peer=Peer(service_name=peername,
					role=PeerRole.host,
					consumer=consumer)
			self.links.append(Link(name=nf.name, description=description, role=PeerRole.guest,
						link_type=LinkType.hosting, peers=ArrayOf(Peer)([peer])))




	def _discover_k8s_links_pods(self):
		""" Discover K8S links to pods

			This is an oversimplification: indeed, kude-admin (hosted on master) controls kubelets (hosted on slaves),
			and kubelets controls pods. The first relationship should be build by _discover_k8s_links_nodes().
		"""

		k8s_service = self.get_services(name=Name(Hostname(self._k8s_dns_name(name='kubernetes',
																								namespace="default",
																								resource_type="svc"))),
													filter=API)

		k8s_pods = self.get_services(filter=Pod)

		for s in k8s_service:
			for p in k8s_pods:
				peer = Peer(service_name=p.name,
							role=PeerRole.controlled, # Kubernetes controls its pods
							consumer=None)
				description="Kubernetes controls pod "+str(p.name.getObj())
				self.links.append(Link(name=s.name, description=description,
							link_type=LinkType.controlling, peers=ArrayOf(Peer)([peer])))


	def _discover_k8s_routers(self):
		""" Discover kubernetes "routers"

			Routers are not resources exposed by kubernets, however, a routing function is present in each
			node to deliver packets within the nodes and external networks.
		"""
		nodes = self._k8s_node_list()

		for n in nodes:
			# Each node will also host a router to implement the cluster network
			router = NetworkFunction(name=n.metadata.name, id=None,
					description="Kubernetes router",type=NetworkFunctionType(Router()))
			self.services.append(Service(name=Name(Hostname(self._k8s_dns_name(name=n.metadata.name, resource_type="router"))), 
						type=ServiceType(router), 
						subservices=None, owner=self.owner, release=n.metadata.resource_version))


	def _discover_k8s_nodes(self):
		""" Discover kubernetes working nodes

			Nodes are the physical servers/vms that host pods. It is questionable if such service 
			should be reported, since the ExecutionEnvironment subsystem should have its own actuator describing 
			the full stack of services/software hosted.
		"""
		nodes = self._k8s_node_list()

		for n in nodes:
			# A Kubernetes node is an execution environment and hosts a kubelet
			node = ExecutionEnvironment(hostname=n.metadata.name, id=n.metadata.uid,
						description="Kubernetes node"+n.status.node_info.container_runtime_version,
                  os= OS(family=n.status.node_info.operating_system, name=n.status.node_info.os_image))
			logger.debug("Found node: %s", str(node))

			self.services.append(Service(name=Name(Hostname(self._k8s_dns_name(name=n.metadata.name, resource_type="node"))), 
						type=ServiceType(node), 
						subservices=None, owner=self.owner, release=n.metadata.resource_version))

			kubelet = Application(name="kubelet", description="Kubernetes worker node",
					version=n.status.node_info.kubelet_version , owner=self.owner, app_type="kubelet")

			self.services.append(Service(name=Name(Hostname(kubelet.name+"@"+str(node.hostname))),
						type=ServiceType(kubelet), 
						subservices=None, owner=self.owner ))

	def _k8s_node_list(self, field_selector=None, label_selector=None):
		try:
			return self.api_client.list_node(field_selector=field_selector, label_selector=label_selector).items
		except ApiException as e:
			logger.warn("Unable to retrieve node list (do you have cluster-wide access?)")
			logger.debug("Reaseon: %s", e)
			return []
	
	def _discover_k8s_links_np(self):
		""" Add link between Kubernetes and Network Policies

			Network Policies implement sort of a slpf firewall, hence they are a security function. However, they are not
			standalone software, and they are implemented by kubernetes..
		"""
		k8s_service = self.get_services(name=Name(Hostname(self._k8s_dns_name(name='kubernetes',
																								namespace="default",
																								resource_type="svc"))),
													filter=API)

		for s in k8s_service:
			consumer = self.get_consumer(Name("kubernetes-networkpolicies"))
			peer = Peer(service_name=Name("kubernetes-networkpolicies"),
							role=PeerRole.controlled, # Kubernetes controls its Network Policies (indeed, they are controlled by a CNI)
							consumer=consumer)
			description="Kubernetes Network Policies"
			self.links.append(Link(name=s.name, description=description,
							link_type=LinkType.controlling, peers=ArrayOf(Peer)([peer])))

 
	
	def _discover_k8s_pods(self):
		""" Discovers pods

			Discovers pods and describes them including network interfaces and hosted containers.
		"""
		self.nodes = {}
		self.routers = {}
			
		pods = self._k8s_pod_list()
		k8s_subservices = ArrayOf(Name)()

		for pod in pods:
			# pod.status.pod_ip and pod.status.pod_i_ps return wrong values (host ip) and
			# do not include multus networks
			if pod.metadata.annotations is not None and 'k8s.v1.cni.cncf.io/network-status' in pod.metadata.annotations:
				ports = json.loads(pod.metadata.annotations['k8s.v1.cni.cncf.io/network-status'])
				port_list = []
				for p in ports:
					name = p['name'] if 'name' in p else None
					iface = p['iface'] if 'iface' in p else None
					ips = []
					if 'ips' in p:
						for ip in p['ips']:
							ips.append(IPInfo(ip=IPAddress(ip)))
					port_list.append( Port(id=name, description="Pod network interfaces",  iface=iface, ips=ips) )
			pod_type = Pod(description="Kubernetes pod", id=pod.metadata.uid,
				  name=Hostname(pod.metadata.name), namespace=pod.metadata.namespace, ports=port_list)	

			# Get the Containers (init and main) used by this pod
			def _get_container_status(c):
				state='unknown'
				if c.state.running is not None:
					state='running'
				if c.state.waiting is not None:
					state='waiting'
				if c.state.terminated is not None:
					state='terminated'
				return state

			def _get_container_list(containers, description=None):
				container_list = []
				try:
					for c in containers:
						state=_get_container_status(c)
						container_list.append( Container(name=c.name, id=c.container_id, 
								description=description, image=c.image, status=state))
				except:	# no containers
					pass
				return container_list


			container_list = _get_container_list(pod.status.container_statuses, "Kubernetes container") + _get_container_list(pod.status.init_container_statuses, "Kubernetes init container")

			# Create services for each container
			container_name_list = ArrayOf(Name)()
			for c in container_list:
				self.services.append(Service(name=Name(Hostname(self._k8s_dns_name(c.name, pod.metadata.namespace, 
																		pod.metadata.name+".container"))), 
						namespace=pod.metadata.namespace,
						type=ServiceType(c), 
                  subservices=None, owner=self.owner, release=None))
				# This is not convincing! A container is not part of the Pod service, it is hosted!
#				container_name_list.append(Name(Hostname(self._k8s_dns_name(c.name, pod.metadata.namespace, 
#															pod.metadata.name+".container"))))

			# Create the pod service with containers as subservices 
			podname=Name(Hostname(self._k8s_dns_name(pod.metadata.name, pod.metadata.namespace, "pod"))) 
			self.services.append(Service(name= podname,
						namespace=pod.metadata.namespace,
						type=ServiceType(pod_type), #links= ArrayOf(Name)([]),
                  subservices=container_name_list, owner=self.owner, release=pod.metadata.resource_version))
			if pod.spec.node_name != "" and pod.spec.node_name is not None:
				self.nodes[str(podname)]=Name(Hostname(pod.spec.node_name))
				self.routers[str(podname)]=Name(Hostname(self._k8s_dns_name(name=pod.spec.node_name, resource_type="router")))
			else:
				self.nodes[str(podname)]=None
				self.routers[str(podname)]=None

			# Since there is not a clear understanding of the different types of controllers,
			# we create the objects here and update them if we found more pods
			if pod.metadata.owner_references is not None:
				for owner in pod.metadata.owner_references:
					if owner.controller:
						controllername = Name(Hostname(self._k8s_dns_name(owner.name, pod.metadata.namespace, owner.kind)))
						controller_list = self.get_services(name=controllername, namespace=pod.metadata.namespace, filter=Application)
						assert len(controller_list) < 2 # Hopefully, only 1 result will be returned
						if len(controller_list) == 0: # Create a new Application for this controller
							app = Application(name=owner.name, description=owner.kind,
									id=owner.uid, app_type=owner.kind)
							controller = Service(name=controllername, type=ServiceType(app), 
									subservices=ArrayOf(Name)([podname]), release=owner.api_version)
							self.services.append(controller)
						else: # Add subservice to existing instance
							controller_list[0].subservices.append(podname)
					if pod.metadata.namespace == "kube-system" and controllername not in k8s_subservices:
						k8s_subservices.append(controllername)
						

		# The root service: K8S cluster
		# --------------------------------------------------
		# K8S is considered PaaS when managed by an external service provider
		name=self.dns if self.dns is not None  else "kubernetes"
		k8s = Cloud(description='Kubernetes cloud', id=None, name=name, type='IaaS')
		# TODO: Fill in with k8s version/release
		# Subservices are the application in 'kube-system' namespace
#		try:
#			nodes = self._k8s_node_list()
#			for n in nodes:
#				k8s_services.append(self._k8s_dns_name(name=n.metadata.name, resource_type="node"))	
#		except:
#			pass
		self.services.append(Service(name=Name(k8s.name),type=ServiceType(k8s), 
				subservices=k8s_subservices, owner=self.owner, release=None))

	def _k8s_pod_list(self, label_selector=""):
		""" Retrieve the list of pods from the K8S API. """
		array_container = ArrayOf(Service)()

		try:
			if self.namespaces is None:
				return self.api_client.list_pod_for_all_namespaces(label_selector=label_selector).items
		except ApiException as e:
			logger.warn("Unable to retrieve pod list for all namespaces")
			logger.debug("Reason: %s", e)
			return []
		
		try:
			pods = []
			for ns in self.namespaces:
				pods += self.api_client.list_namespaced_pod(namespace=ns, label_selector=label_selector).items 
		except ApiException as e:
			logger.warn("Unable to retrieve pod list for namespace %s", ns)
			logger.warn("Reason: %s", ns , e)

		return pods


	def _discover_np_links_pods(self):
		""" Add links from Network Policies to pods

			Automatically add a link from Network Policies to pods
			Network policies are modelled as a security function implemented by an external actuator.
			They protect all pods hosted in Kubernetes..
		"""
		k8s_service = self.get_services(filter=Pod)

		for s in k8s_service:
			consumer = self.get_consumer(Name("kubernetes-networkpolicies"))
			peer = Peer(service_name=Name("kubernetes-networkpolicies"),
							role=PeerRole.protect, # Kubernetes controls its Network Policies (indeed, they are controlled by a CNI)
							consumer=consumer)
			description="Kubernetes Network Policies protect "+str(s.name)
			self.links.append(Link(name=s.name, description=description, role=PeerRole.protected,
							link_type=LinkType.protecting, peers=ArrayOf(Peer)([peer])))


	def _connect_to_kubernetes(self):
		""" Connects to Kubernetes

			Use the available configuration to carry out authentication to a Kubernetes cluster.
		"""
			
		# The config module loads configuration from .kube (or provided file) into the _default member of the client.Configuration
		# class (which is a class member!). After invoking one of the config method to load these values, the client module
		# has access to such configuration through the Configuration. Note that certificates provided as values in the 
		# configuration file are then stored as files by the Configuration class.

		try:
			configuration = client.Configuration()
			# Configure API key authorization: BearerToken
			configuration.api_key['authorization'] = self.auth['api_key']
			# Uncomment below to setup prefix (e.g. Bearer) for API key, if needed
			configuration.api_key_prefix['authorization'] = 'Bearer'
			# Defining host is optional and default to http://localhost
			configuration.host = self.auth['host']
			# Set the cluster CA	certificate or disable certificate validation
			if self.config is not None and 'cacert' in self.config:
				configuration.ssl_ca_cert=self.config['cacert']
			else:
				configuration.verify_ssl=False
	
			# Create an API client
			self.api_client = client.CoreV1Api(client.ApiClient(configuration))
		except Exception as e:
			logger.error("Failed to connect to kubernetes: ", e)
			return Exception("Failed to connect to kubernetes")
		
	def _k8s_dns_name(self, name: str, namespace: str = None, resource_type: str = None):
		""" Create dns name to identify kubernetes resources

			The name will be the same as the dns name
		"""
		dnsname=name
		if( namespace is not None ):
			dnsname=name+"."+namespace
		if resource_type is not None:
			dnsname+="."+resource_type
		if self.dns is not None:
			dnsname+="."+self.dns

		return dnsname

	def _setup_cni(self):
		if self.cniconfig is None:
			return


		self.cni_cluster_cidr = None
		self.cni_service_cidr = None
		try:
			if 'file' in self.cniconfig:
				with open(self.cniconfig['file']) as f:
					config = yaml.safe_load(f)
					for cmds in  config['spec']['containers']:
						if 'command' in cmds:
							for cmd in cmds['command']:
								pair=cmd.replace("--",'',1)
								l=pair.split('=',1)
								if l[0] == "cluster-cidr":
									self.cni_cluster_cidr = l[1]
								if l[0] == "service-cluster-ip-range":
									self.cni_service_cidr = l[1]
		except Exception as e:
			logger.error("Unable to parse cni config file: %s", e)

		try:
			if self.cni_cluster_cidr == None or self.cni_service_cidr == None:
				self.cni_cluster_cidr = self.cniconfig['cluster-cidr']
				self.cni_service_cidr = self.cniconfig['service-cluster-ip-range']
		except Exception as e:
			logger.error("Unable to get cluster IP addresses from configuration: %s", e)

