ctxd-openstack-example:
  actuator: "ctxd-openstack"
  profile: "x-ctxd"
  owner: "tnt-lab"
  specifiers:
    domain: null
    asset_id: "ctxd-openstack-example"
  consumer:
    host: "something"
    port: 8080
    protocol: "tcp"
    endpoint: "/.well-known/openc2"
    transfer: "http"
    encoding: "json"
  auth:
    username: "matteo"
    password: "xxxxx"
    project_name: "xxxxx"
    user_domain_name: "Default"
    project_domain_name: "Default"
    auth_url: "https://xxxxx"
  config:
#    identity_api_version: 3
    cacert: "xxxxx"
  peers:
    - service_name: 
        local: kube0
      consumer:
        host: "kube0"
        port: 8080
        actuator:
          asset_id: "ctxd-kube0"
    - service_name: openstack-securitygroups
      consumer:
        host: "127.0.0.1"
        port: 8080
        profile: slpf
        actuator:
          asset_id: "sg"  
